// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenFlowCRMModels.Models
{
    public partial class Carichi
    {
        public long Idcarico { get; set; }
        public DateTime DataConsegna { get; set; }
        public string Note { get; set; }
    }
}