// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenFlowCRMModels.Models
{
    public partial class CatalogoModelli
    {
        public CatalogoModelli()
        {
            ComponenteMerceCatalogoModelli = new HashSet<ComponenteMerceCatalogoModelli>();
            Partite = new HashSet<Partite>();
        }

        public long Id { get; set; }
        public string Descrizione { get; set; }
        public int? Lunghezza { get; set; }
        public int? Larghezza { get; set; }
        public int? Altezza { get; set; }

        public virtual ICollection<ComponenteMerceCatalogoModelli> ComponenteMerceCatalogoModelli { get; set; }
        public virtual ICollection<Partite> Partite { get; set; }
    }
}