// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace OpenFlowCRMModels.Models
{
    [Serializable]
    public partial class Clienti
    {
        public Clienti()
        {
            Ordini = new HashSet<Ordini>();
        }

        public long Idcliente { get; set; }
        public string Nome { get; set; }
        public string Indirizzo { get; set; }
        public string Note { get; set; }

        [JsonIgnore]
        public virtual ICollection<Ordini> Ordini { get; set; }
    }
}