// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenFlowCRMModels.Models
{
    public partial class ComponenteMerceCatalogoModelli
    {
        public long ComponenteMerceId { get; set; }
        public long CatalogoModelliId { get; set; }
        public int Quantita { get; set; }

        public virtual ComponentiMerce ComponenteMerce { get; set; }
        public virtual CatalogoModelli CatalogoModelli { get; set; }
    }
}