// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenFlowCRMModels.Models
{
    public partial class ComponentiMerce
    {
        public ComponentiMerce()
        {
            ComponenteMerceCatalogoModelli = new HashSet<ComponenteMerceCatalogoModelli>();
        }

        public long IdcomponenteMerce { get; set; }
        public string TipoComponente { get; set; }
        public string MaterialeComponente { get; set; }
        public int? Lunghezza { get; set; }
        public int? Larghezza { get; set; }
        public int? Altezza { get; set; }
        public string Note { get; set; }

        public virtual ICollection<ComponenteMerceCatalogoModelli> ComponenteMerceCatalogoModelli { get; set; }
    }
}