// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenFlowCRMModels.Models
{
    public partial class Lotti
    {
        public long LottoId { get; set; }
        public string Nome { get; set; }
        public int Lunghezza { get; set; }
        public int Larghezza { get; set; }
        public int Altezza { get; set; }
        public int Quantita { get; set; }
        public string TipoMateriale { get; set; }
        public STATO_LOTTO Stato { get; set; }
        public DateTime? DataInizioPrevista { get; set; }
        public DateTime? DataFinePrevista { get; set; }
        public DateTime? DataInizioEffettiva { get; set; }
        public DateTime? DataFineEffettiva { get; set; }
        public string Note { get; set; }
        public long? MacchinaAssegnata { get; set; }
    }
}