// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenFlowCRMModels.Models
{
    [Serializable]
    public partial class Macchine
    {
        public long MacchineId { get; set; }
        public long LottoCorrente { get; set; }
        public string Descrizione { get; set; }
        public string Name { get; set; }
        public string Ip { get; set; }
        public long? RisorseUmane { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    }
}