// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenFlowCRMModels.Models
{
    [Serializable]
    public partial class Ordini
    {
        public Ordini()
        {
            Partite = new HashSet<Partite>();
        }

        public long OrdiniId { get; set; }
        public string Descrizione { get; set; }
        public long Cliente { get; set; }

        public virtual Clienti ClienteNavigation { get; set; }
        public virtual ICollection<Partite> Partite { get; set; }
    }
}